# Generated by Django 3.1.1 on 2022-02-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220212_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img',
        ),
        migrations.RemoveField(
            model_name='products',
            name='offer',
        ),
    ]
