# Generated by Django 3.1.1 on 2022-02-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_products_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
        migrations.AddField(
            model_name='post',
            name='bed_room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='belcony',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='drawing_room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='dyning_room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='wash_room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
