# Generated by Django 3.1.1 on 2022-02-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_post_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='author',
        ),
    ]
