# Generated by Django 3.1.1 on 2022-03-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_location_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
