# Generated by Django 3.1.1 on 2022-03-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
