# Generated by Django 3.1.1 on 2022-03-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
