# Generated by Django 3.1.1 on 2022-03-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rent_to',
        ),
    ]
