# Generated by Django 3.1.1 on 2022-03-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='feedback',
        ),
    ]
