# Generated by Django 3.1.1 on 2022-03-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_auto_20220313_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
