# Generated by Django 3.1.1 on 2022-03-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
